# Generated by Django 6.0.3 on 2026-06-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_purchaseorder_received_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotification',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffnotification',
            name='source_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staffnotification',
            name='target_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='staffnotification',
            name='notification_type',
            field=models.CharField(choices=[('po_approval', 'PO Approval'), ('po_decision', 'PO Decision'), ('mention', 'Mention'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
