# Generated by Django 6.0.3 on 2026-06-28 19:08

from django.db import migrations, models


def seed_locations(apps, schema_editor):
    AssetLocation = apps.get_model("assets", "AssetLocation")
    AssetLocation.objects.get_or_create(name="Leicester Depot", defaults={"kind": "depot"})


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('depot', 'Depot'), ('office', 'Office'), ('vehicle', 'Vehicle'), ('storage', 'Storage'), ('other', 'Other')], default='depot', max_length=30)),
                ('address', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_locations, migrations.RunPython.noop),
    ]
