# Generated by Django 6.0.3 on 2026-03-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haulierrate',
            old_name='rental_per_day',
            new_name='excess_per_kg',
        ),
        migrations.AddField(
            model_name='haulierrate',
            name='weight_limit_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
