# Generated by Django 6.0.3 on 2026-04-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauliers', '0003_portal_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haulierportaluser',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='haulierportaluser',
            name='portal_pin',
        ),
        migrations.AddField(
            model_name='haulierportaluser',
            name='must_set_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='haulierportaluser',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='haulierportaluser',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='haulierportaluser',
            name='password_reset_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
