# Generated by Django 6.0.3 on 2026-06-28 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hauliers', '0004_rename_active_haulierportaluser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='haulier',
            name='account_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='haulier',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='haulier',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='haulier',
            name='environmental_permit',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='haulier',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='haulier',
            name='payment_terms_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='haulier',
            name='sla_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='haulier',
            name='waste_carrier_license',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='haulier',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='haulierrate',
            name='waste_type',
            field=models.CharField(choices=[('general', 'General Waste'), ('mixed_recycling', 'Mixed Recycling'), ('cardboard', 'Cardboard'), ('glass', 'Glass'), ('food', 'Food'), ('paper', 'Paper')], max_length=20),
        ),
        migrations.CreateModel(
            name='HaulierCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('general', 'General Waste'), ('mixed_recycling', 'Mixed Recycling'), ('cardboard', 'Cardboard'), ('glass', 'Glass'), ('food', 'Food'), ('paper', 'Paper')], max_length=30)),
                ('postcode_area', models.CharField(max_length=80)),
                ('collection_days', models.JSONField(blank=True, default=list)),
                ('service_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('adhoc', 'Ad hoc'), ('both', 'Scheduled and ad hoc')], default='scheduled', max_length=20)),
                ('lead_time_days', models.PositiveSmallIntegerField(default=2)),
                ('minimum_lift_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_surcharge_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('requires_po', models.BooleanField(default=False)),
                ('booking_cutoff', models.CharField(blank=True, max_length=80)),
                ('vehicle_notes', models.TextField(blank=True)),
                ('restrictions', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('haulier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_entries', to='hauliers.haulier')),
            ],
            options={
                'ordering': ['haulier__name', 'postcode_area', 'waste_type'],
                'indexes': [models.Index(fields=['waste_type', 'postcode_area'], name='hauliers_ha_waste_t_c2d200_idx'), models.Index(fields=['haulier', 'active'], name='hauliers_ha_haulier_d95550_idx')],
            },
        ),
    ]
