# Generated by Django 6.0.3 on 2026-03-18 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_rename_billing_address_line_1_customer_address_line_1_and_more'),
        ('services', '0002_alter_service_waste_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('failed', 'Failed')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_events', to='customers.customer')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_events', to='services.service')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_events', to='customers.site')),
            ],
            options={
                'ordering': ['-date_time', '-id'],
            },
        ),
    ]
