# Generated by Django 6.0.3 on 2026-03-17 23:04

import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quotedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotedocument',
            name='file',
            field=models.FileField(upload_to=quotes.models.quote_document_upload_to),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='rental_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
