# Generated by Django 6.0.3 on 2026-04-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quotedocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='sic_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
