# Generated by Django 6.0.3 on 2026-03-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('general', 'General Waste'), ('recycling', 'Dry Mixed Recycling'), ('glass', 'Glass'), ('food', 'Food')], max_length=20)),
                ('bin_size', models.CharField(choices=[('240', '240L'), ('360', '360L'), ('660', '660L'), ('1100', '1100L')], max_length=10)),
                ('price_per_lift', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['waste_type', 'bin_size'],
                'unique_together': {('waste_type', 'bin_size')},
            },
        ),
    ]
