# Generated by Django 6.0.3 on 2026-03-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricebookitem_rental_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricebookitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
