# Generated by Django 6.0.3 on 2026-03-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('general', 'General Waste'), ('recycling', 'Dry Mixed Recycling'), ('glass', 'Glass'), ('food', 'Food')], max_length=20)),
                ('bin_size', models.CharField(choices=[('240', '240L'), ('360', '360L'), ('660', '660L'), ('1100', '1100L')], max_length=10)),
                ('bin_count', models.PositiveIntegerField(default=1)),
                ('collections_per_week', models.PositiveIntegerField(default=1)),
                ('lock_required', models.BooleanField(default=False)),
                ('metal_bin_required', models.BooleanField(default=False)),
                ('price_per_lift', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='customers.customer')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='customers.site')),
            ],
        ),
    ]
