# Generated by Django 6.0.3 on 2026-03-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='waste_type',
            field=models.CharField(choices=[('general', 'General Waste'), ('mixed_recycling', 'Mixed Recycling'), ('glass', 'Glass'), ('food', 'Food')], max_length=20),
        ),
    ]
