# Generated by Django 6.0.3 on 2026-04-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_ops_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='schedule_start_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='collection_days',
        ),
        migrations.AddField(
            model_name='service',
            name='collection_day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('multiple_per_week', 'Multiple Per Week'), ('ad_hoc', 'Ad Hoc')], default='weekly', max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('pending_schedule', 'Pending Schedule'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='pending_schedule', max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='waste_type',
            field=models.CharField(choices=[('general', 'General Waste'), ('mixed_recycling', 'Mixed Recycling'), ('glass', 'Glass'), ('food', 'Food')], max_length=30),
        ),
    ]
