# Generated by Django 6.0.3 on 2026-04-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='start_date',
            new_name='schedule_start_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='collection_day',
        ),
        migrations.RemoveField(
            model_name='service',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='service',
            name='collection_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='service',
            name='schedule_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('on_request', 'On Request')], default='weekly', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='waste_type',
            field=models.CharField(choices=[('general', 'General Waste'), ('mixed_recycling', 'Mixed Recycling'), ('glass', 'Glass'), ('food', 'Food')], max_length=20),
        ),
    ]
