# Generated by Django 6.0.3 on 2026-03-18 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_billing_address_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='billing_address_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='billing_address_line_2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='primary_contact_name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='billing_county',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='billing_postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='billing_town',
            new_name='town',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='secondary_contact_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='secondary_phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='trading_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vat_number',
        ),
        migrations.RemoveField(
            model_name='site',
            name='address',
        ),
        migrations.RemoveField(
            model_name='site',
            name='email',
        ),
        migrations.RemoveField(
            model_name='site',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='site',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='site',
            name='primary_contact_name',
        ),
        migrations.RemoveField(
            model_name='site',
            name='secondary_contact_name',
        ),
        migrations.RemoveField(
            model_name='site',
            name='secondary_phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
