# Generated by Django 6.0.3 on 2026-03-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_rename_billing_address_line_1_customer_address_line_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("note", "Note"),
                            ("quote", "Quote"),
                            ("service", "Service"),
                            ("pdf", "PDF"),
                            ("email", "Email"),
                            ("collection", "Collection"),
                        ],
                        default="system",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_by", models.CharField(blank=True, max_length=255)),
                ("related_quote_number", models.CharField(blank=True, max_length=50)),
                ("related_service_id", models.PositiveIntegerField(blank=True, null=True)),
                ("related_document_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_entries",
                        to="customers.customer",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_entries",
                        to="customers.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]