# Generated by Django 6.0.3 on 2026-04-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customeractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sic_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
