# Generated by Django 6.0.3 on 2026-06-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_seed_customer_portal_test_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoice_cycle_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
