# Generated by Django 6.0.3 on 2026-06-14 18:52

from django.db import migrations, models


def deactivate_fuel_category(apps, schema_editor):
    ExpenseCategory = apps.get_model("expenses", "ExpenseCategory")
    ExpenseCategory.objects.filter(name__iexact="Fuel").update(active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseclaim',
            name='expense_type',
            field=models.CharField(choices=[('general', 'General Expense'), ('mileage', 'Mileage')], default='general', max_length=20),
        ),
        migrations.RunPython(deactivate_fuel_category, migrations.RunPython.noop),
    ]
