# Generated by Django 6.0.3 on 2026-06-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expenseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseline',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
