# Generated by Django 6.0.3 on 2026-04-01 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_customeractivity'),
        ('services', '0003_service_ops_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('waste_type', models.CharField(max_length=100)),
                ('bin_size', models.CharField(max_length=50)),
                ('bin_quantity', models.IntegerField()),
                ('haulier', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('collected', 'Collected'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('failure_reason', models.CharField(blank=True, choices=[('blocked_access', 'Blocked Access'), ('not_presented', 'Bin Not Presented'), ('contaminated', 'Contaminated'), ('overweight', 'Overweight'), ('closed', 'Site Closed'), ('other', 'Other')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='services.service')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.site')),
            ],
        ),
    ]
