# Generated by Django 6.0.3 on 2026-04-04 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_customeractivity'),
        ('quotes', '0003_alter_quotedocument_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('service_agreement', 'Service Agreement'), ('service_schedule', 'Service Schedule'), ('duty_of_care', 'Duty of Care / Waste Transfer Note')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='generated_documents/')),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('sent', 'Sent'), ('signed', 'Signed')], default='generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='customers.customer')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='quotes.quote')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='customers.site')),
            ],
        ),
    ]
