# Generated by Django 6.0.3 on 2026-06-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_signingpack_acceptance_service_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingpack',
            name='invoice_payment_terms_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='signingpack',
            name='invoice_requires_po',
            field=models.BooleanField(default=False),
        ),
    ]
