# Generated by Django 6.0.3 on 2026-06-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0005_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='mailbox_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='mailbox_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
