# Generated by Django 6.0.3 on 2026-06-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0007_staffprofile_auto_assign_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='mileage_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company_name',
            field=models.CharField(default='Recyclr Group Ltd', max_length=200),
        ),
    ]
