# Generated by Django 6.0.3 on 2026-06-14 18:52

from django.db import migrations, models


def copy_staff_mileage_rate_to_company(apps, schema_editor):
    StaffProfile = apps.get_model("accounts_api", "StaffProfile")
    CompanyDetails = apps.get_model("accounts_api", "CompanyDetails")

    mileage_rate = (
        StaffProfile.objects.exclude(mileage_rate=0)
        .order_by("-mileage_rate")
        .values_list("mileage_rate", flat=True)
        .first()
    )
    if mileage_rate is None:
        return

    details, _ = CompanyDetails.objects.get_or_create(singleton_key=1)
    details.mileage_rate = mileage_rate
    details.save(update_fields=["mileage_rate", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0008_staffprofile_mileage_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='mileage_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.RunPython(copy_staff_mileage_rate_to_company, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='staffprofile',
            name='mileage_rate',
        ),
    ]
