# Generated by Django 6.0.3 on 2026-06-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0010_companydetails_container_label_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
