# Generated by Django 6.0.3 on 2026-06-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0011_companydetails_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='company_email_domain',
            field=models.CharField(blank=True, default='recyclrgroup.co.uk', max_length=150),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='default_quote_validity_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='default_target_margin_percent',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=6),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='signing_pack_expiry_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
