# Generated by Django 6.0.3 on 2026-06-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0008_customer_customer_uid'),
        ('services', '0007_alter_service_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_size', models.CharField(choices=[('240', '240L'), ('360', '360L'), ('660', '660L'), ('1100', '1100L')], max_length=10)),
                ('waste_stream', models.CharField(choices=[('general', 'General Waste'), ('mixed_recycling', 'Mixed Recycling'), ('cardboard', 'Cardboard'), ('glass', 'Glass'), ('food', 'Food'), ('paper', 'Paper')], max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_uid', models.CharField(blank=True, max_length=40, unique=True)),
                ('bin_size', models.CharField(choices=[('240', '240L'), ('360', '360L'), ('660', '660L'), ('1100', '1100L')], max_length=10)),
                ('waste_stream', models.CharField(choices=[('general', 'General Waste'), ('mixed_recycling', 'Mixed Recycling'), ('cardboard', 'Cardboard'), ('glass', 'Glass'), ('food', 'Food'), ('paper', 'Paper')], max_length=30)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('assigned', 'Assigned'), ('active', 'Active'), ('maintenance', 'Maintenance'), ('eol', 'EOL')], default='inactive', max_length=20)),
                ('qr_payload', models.CharField(blank=True, max_length=255)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('eol_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='services.service')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='customers.site')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='containers.containerbatch')),
            ],
            options={
                'ordering': ['container_uid', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContainerMaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('eol', 'Marked EOL')], default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('reported_by', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_events', to='containers.container')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
