# Generated by Django 6.0.3 on 2026-06-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('inactive', 'In Stock'), ('assigned', 'Assigned'), ('active', 'Active'), ('maintenance', 'Maintenance'), ('eol', 'EOL')], default='inactive', max_length=20),
        ),
    ]
