# Generated by Codex on 2026-06-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0002_alter_container_status"),
        ("customers", "0012_seed_customer_portal_test_account"),
        ("services", "0007_alter_service_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery"),
                            ("collection", "Collection"),
                            ("replacement_delivery", "Replacement Delivery"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                (
                    "waste_stream",
                    models.CharField(
                        choices=[
                            ("general", "General Waste"),
                            ("mixed_recycling", "Mixed Recycling"),
                            ("cardboard", "Cardboard"),
                            ("glass", "Glass"),
                            ("food", "Food"),
                            ("paper", "Paper"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "bin_size",
                    models.CharField(
                        choices=[
                            ("240", "240L"),
                            ("360", "360L"),
                            ("660", "660L"),
                            ("1100", "1100L"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("reason", models.TextField(blank=True)),
                ("created_by", models.CharField(blank=True, max_length=255)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("billable_to_customer", models.BooleanField(default=False)),
                ("charge_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("charge_reason", models.CharField(blank=True, max_length=255)),
                ("billed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="containers.container",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_movements",
                        to="customers.customer",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="container_movements",
                        to="services.service",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_movements",
                        to="customers.site",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date", "id"],
            },
        ),
    ]
