# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("containers", "0003_containermovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="containermovement",
            name="completion_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="containermovement",
            name="customer_present",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="containermovement",
            name="photo_data",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="containermovement",
            name="qr_scan_value",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="containermovement",
            name="signature_data",
            field=models.TextField(blank=True),
        ),
    ]
