# Generated by Django 6.0.3 on 2026-03-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_rename_estimated_bins_lead_food_bins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='current_provider',
        ),
        migrations.AddField(
            model_name='lead',
            name='additional_provider_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='additional_provider_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='food_current_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='general_waste_current_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='glass_current_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='recycling_current_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
