# Generated by Django 6.0.3 on 2026-03-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_lead_current_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='additional_provider_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='additional_provider_notes',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='food_bins',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='general_waste_bins',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='glass_bins',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='recycling_bins',
        ),
        migrations.AddField(
            model_name='lead',
            name='food_bin_count',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50')], null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='food_bin_size',
            field=models.CharField(blank=True, choices=[('240', '240L'), ('360', '360L'), ('660', '660L'), ('1100', '1100L')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='food_contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='food_current_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='food_is_broker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='food_lock_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='food_metal_bin_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='general_waste_bin_count',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50')], null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='general_waste_bin_size',
            field=models.CharField(blank=True, choices=[('240', '240L'), ('360', '360L'), ('660', '660L'), ('1100', '1100L')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='general_waste_contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='general_waste_current_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='general_waste_is_broker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='general_waste_lock_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='general_waste_metal_bin_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='glass_bin_count',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50')], null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='glass_bin_size',
            field=models.CharField(blank=True, choices=[('240', '240L'), ('360', '360L'), ('660', '660L'), ('1100', '1100L')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='glass_contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='glass_current_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='glass_is_broker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='glass_lock_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='glass_metal_bin_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='recycling_bin_count',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50')], null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='recycling_bin_size',
            field=models.CharField(blank=True, choices=[('240', '240L'), ('360', '360L'), ('660', '660L'), ('1100', '1100L')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='recycling_contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='recycling_current_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='recycling_is_broker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='recycling_lock_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='recycling_metal_bin_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='food_collections_per_week',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50')], null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='general_waste_collections_per_week',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50')], null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='glass_collections_per_week',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50')], null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='recycling_collections_per_week',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50')], null=True),
        ),
    ]
