# Generated by Django 6.0.3 on 2026-03-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_site'),
        ('leads', '0005_remove_lead_additional_provider_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='customers.customer'),
        ),
    ]
