# Generated by Django 6.0.3 on 2026-03-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_converted_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='food_bin_size',
            field=models.CharField(blank=True, choices=[('240', '240L')], default='240', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='glass_bin_size',
            field=models.CharField(blank=True, choices=[('240', '240L')], default='240', max_length=10),
        ),
    ]
