# Generated by Django 6.0.3 on 2026-03-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_lead_food_bin_size_alter_lead_glass_bin_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='estimated_monthly_value',
        ),
    ]
