# Generated by Django 6.0.3 on 2026-03-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_remove_lead_estimated_monthly_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
