# Generated by Django 6.0.3 on 2026-04-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_address_line_1_lead_address_line_2_lead_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sic_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
